# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: baae08f90a47f1301e05bc1aec281fce917beeb141bed3170a8c183e7825b3e38d85daa27dbedfd984d967a54d1684ff218419295a78f4c23b225c742ddba26a

test:
  secret_key_base: 2b3f69053db91865e0200bc5670df803ee18ec42718fab484938910cce3256d14f79ad9cc81b1194b907517c654e41175f5860ad8cc83bde5264dc141c44085d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
